# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '总设计.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MdiArea(object):
    def setupUi(self, MdiArea):
        MdiArea.setObjectName("MdiArea")
        MdiArea.resize(1218, 824)
        MdiArea.setMinimumSize(QtCore.QSize(941, 638))
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        # MdiArea.setBackground(brush)
        self.MainWindow = QtWidgets.QWidget()
        self.MainWindow.setObjectName("MainWindow")
        self.Book = QtWidgets.QPushButton(self.MainWindow)
        self.Book.setGeometry(QtCore.QRect(340, 210, 211, 61))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Book.setFont(font)
        self.Book.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/read.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Book.setIcon(icon)
        self.Book.setIconSize(QtCore.QSize(60, 45))
        self.Book.setObjectName("Book")
        self.Game = QtWidgets.QPushButton(self.MainWindow)
        self.Game.setGeometry(QtCore.QRect(340, 330, 211, 61))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Game.setFont(font)
        self.Game.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icon/game.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Game.setIcon(icon1)
        self.Game.setIconSize(QtCore.QSize(50, 50))
        self.Game.setObjectName("Game")
        self.WelcomeAndName = QtWidgets.QLabel(self.MainWindow)
        self.WelcomeAndName.setGeometry(QtCore.QRect(50, 50, 661, 41))
        self.WelcomeAndName.setObjectName("WelcomeAndName")
        self.LvNum = QtWidgets.QLCDNumber(self.MainWindow)
        self.LvNum.setGeometry(QtCore.QRect(780, 50, 31, 41))
        self.LvNum.setSmallDecimalPoint(False)
        self.LvNum.setDigitCount(1)
        self.LvNum.setMode(QtWidgets.QLCDNumber.Dec)
        self.LvNum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.LvNum.setProperty("value", 1.0)
        self.LvNum.setProperty("intValue", 1)
        self.LvNum.setObjectName("LvNum")
        self.LvLabel = QtWidgets.QLabel(self.MainWindow)
        self.LvLabel.setGeometry(QtCore.QRect(740, 50, 41, 41))
        self.LvLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LvLabel.setObjectName("LvLabel")
        self.BookWindow = QtWidgets.QWidget()
        self.BookWindow.setObjectName("BookWindow")
        self.mingzhupaihang = QtWidgets.QLabel(self.BookWindow)
        self.mingzhupaihang.setGeometry(QtCore.QRect(410, 20, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.mingzhupaihang.setFont(font)
        self.mingzhupaihang.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mingzhupaihang.setObjectName("mingzhupaihang")
        self.line = QtWidgets.QFrame(self.BookWindow)
        self.line.setGeometry(QtCore.QRect(100, 120, 721, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.BookWindow)
        self.line_2.setGeometry(QtCore.QRect(100, 160, 721, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.BookWindow)
        self.line_3.setGeometry(QtCore.QRect(100, 200, 721, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.BookWindow)
        self.line_4.setGeometry(QtCore.QRect(100, 240, 721, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.BookWindow)
        self.line_5.setGeometry(QtCore.QRect(100, 280, 721, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.BookWindow)
        self.line_6.setGeometry(QtCore.QRect(100, 320, 721, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.BookWindow)
        self.line_7.setGeometry(QtCore.QRect(100, 360, 721, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.BookWindow)
        self.line_8.setGeometry(QtCore.QRect(100, 400, 721, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.BookWindow)
        self.line_9.setGeometry(QtCore.QRect(100, 440, 721, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.BookWindow)
        self.line_10.setGeometry(QtCore.QRect(100, 480, 721, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.Book0 = QtWidgets.QPushButton(self.BookWindow)
        self.Book0.setGeometry(QtCore.QRect(100, 90, 721, 31))
        self.Book0.setObjectName("Book0")
        self.Book1 = QtWidgets.QPushButton(self.BookWindow)
        self.Book1.setGeometry(QtCore.QRect(100, 130, 721, 31))
        self.Book1.setObjectName("Book1")
        self.Book2 = QtWidgets.QPushButton(self.BookWindow)
        self.Book2.setGeometry(QtCore.QRect(100, 170, 721, 31))
        self.Book2.setObjectName("Book2")
        self.Book3 = QtWidgets.QPushButton(self.BookWindow)
        self.Book3.setGeometry(QtCore.QRect(100, 210, 721, 31))
        self.Book3.setObjectName("Book3")
        self.Book4 = QtWidgets.QPushButton(self.BookWindow)
        self.Book4.setGeometry(QtCore.QRect(100, 250, 721, 31))
        self.Book4.setObjectName("Book4")
        self.Book5 = QtWidgets.QPushButton(self.BookWindow)
        self.Book5.setGeometry(QtCore.QRect(100, 290, 721, 31))
        self.Book5.setObjectName("Book5")
        self.Book6 = QtWidgets.QPushButton(self.BookWindow)
        self.Book6.setGeometry(QtCore.QRect(100, 330, 721, 31))
        self.Book6.setObjectName("Book6")
        self.Book7 = QtWidgets.QPushButton(self.BookWindow)
        self.Book7.setGeometry(QtCore.QRect(100, 370, 721, 31))
        self.Book7.setObjectName("Book7")
        self.Book8 = QtWidgets.QPushButton(self.BookWindow)
        self.Book8.setGeometry(QtCore.QRect(100, 410, 721, 31))
        self.Book8.setObjectName("Book8")
        self.Book9 = QtWidgets.QPushButton(self.BookWindow)
        self.Book9.setGeometry(QtCore.QRect(100, 450, 721, 31))
        self.Book9.setObjectName("Book9")
        self.BookBack = QtWidgets.QPushButton(self.BookWindow)
        self.BookBack.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.BookBack.setObjectName("BookBack")
        self.GameWindow = QtWidgets.QWidget()
        self.GameWindow.setObjectName("GameWindow")
        self.GameBack = QtWidgets.QPushButton(self.GameWindow)
        self.GameBack.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.GameBack.setObjectName("GameBack")
        self.youxiyule = QtWidgets.QLabel(self.GameWindow)
        self.youxiyule.setGeometry(QtCore.QRect(350, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.youxiyule.setFont(font)
        self.youxiyule.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.youxiyule.setObjectName("youxiyule")
        self.yizhi = QtWidgets.QPushButton(self.GameWindow)
        self.yizhi.setGeometry(QtCore.QRect(320, 150, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.yizhi.setFont(font)
        self.yizhi.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icon/yizhi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yizhi.setIcon(icon2)
        self.yizhi.setIconSize(QtCore.QSize(45, 45))
        self.yizhi.setObjectName("yizhi")
        self.celue = QtWidgets.QPushButton(self.GameWindow)
        self.celue.setGeometry(QtCore.QRect(320, 230, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.celue.setFont(font)
        self.celue.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icon/celue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.celue.setIcon(icon3)
        self.celue.setIconSize(QtCore.QSize(45, 45))
        self.celue.setObjectName("celue")
        self.duizhan = QtWidgets.QPushButton(self.GameWindow)
        self.duizhan.setGeometry(QtCore.QRect(320, 310, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.duizhan.setFont(font)
        self.duizhan.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icon/duizhan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.duizhan.setIcon(icon4)
        self.duizhan.setIconSize(QtCore.QSize(45, 45))
        self.duizhan.setObjectName("duizhan")
        self.zonghe = QtWidgets.QPushButton(self.GameWindow)
        self.zonghe.setGeometry(QtCore.QRect(320, 390, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.zonghe.setFont(font)
        self.zonghe.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icon/zonghe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zonghe.setIcon(icon5)
        self.zonghe.setIconSize(QtCore.QSize(45, 45))
        self.zonghe.setObjectName("zonghe")
        self.ContainWindow = QtWidgets.QWidget()
        self.ContainWindow.setObjectName("ContainWindow")
        self.BookName = QtWidgets.QLabel(self.ContainWindow)
        self.BookName.setGeometry(QtCore.QRect(100, 20, 1001, 51))
        self.BookName.setText("")
        self.BookName.setAlignment(QtCore.Qt.AlignCenter)
        self.BookName.setObjectName("BookName")
        self.ContainBack = QtWidgets.QPushButton(self.ContainWindow)
        self.ContainBack.setGeometry(QtCore.QRect(10, 30, 121, 31))
        self.ContainBack.setObjectName("ContainBack")
        self.Chapter = QtWidgets.QComboBox(self.ContainWindow)
        self.Chapter.setGeometry(QtCore.QRect(500, 90, 201, 22))
        self.Chapter.setObjectName("Chapter")
        self.BookContain = QtWidgets.QTextBrowser(self.ContainWindow)
        self.BookContain.setGeometry(QtCore.QRect(10, 140, 1151, 611))
        self.BookContain.setObjectName("BookContain")
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        self.BookContain.setFont(font)
        self.Chapter.raise_()
        self.BookName.raise_()
        self.ContainBack.raise_()
        self.BookContain.raise_()
        self.LoginWindow = QtWidgets.QWidget()
        self.LoginWindow.setObjectName("LoginWindow")
        self.UserNameLabel = QtWidgets.QLabel(self.LoginWindow)
        self.UserNameLabel.setGeometry(QtCore.QRect(60, 90, 51, 31))
        self.UserNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.UserNameLabel.setObjectName("UserNameLabel")
        self.UserPasswordLabel = QtWidgets.QLabel(self.LoginWindow)
        self.UserPasswordLabel.setGeometry(QtCore.QRect(60, 140, 51, 16))
        self.UserPasswordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.UserPasswordLabel.setObjectName("UserPasswordLabel")
        self.WelcomeLabel = QtWidgets.QLabel(self.LoginWindow)
        self.WelcomeLabel.setGeometry(QtCore.QRect(40, 20, 411, 41))
        self.WelcomeLabel.setScaledContents(False)
        self.WelcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.WelcomeLabel.setWordWrap(False)
        self.WelcomeLabel.setIndent(-1)
        self.WelcomeLabel.setObjectName("WelcomeLabel")
        self.UserNameInput = QtWidgets.QLineEdit(self.LoginWindow)
        self.UserNameInput.setGeometry(QtCore.QRect(160, 100, 241, 21))
        self.UserNameInput.setObjectName("UserNameInput")
        self.UserPaswordInput = QtWidgets.QLineEdit(self.LoginWindow)
        self.UserPaswordInput.setGeometry(QtCore.QRect(160, 140, 241, 21))
        self.UserPaswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.UserPaswordInput.setObjectName("UserPaswordInput")
        self.LoginButton = QtWidgets.QPushButton(self.LoginWindow)
        self.LoginButton.setGeometry(QtCore.QRect(160, 190, 93, 28))
        self.LoginButton.setDefault(False)
        self.LoginButton.setFlat(False)
        self.LoginButton.setObjectName("LoginButton")
        self.GoToRegisterButton = QtWidgets.QPushButton(self.LoginWindow)
        self.GoToRegisterButton.setGeometry(QtCore.QRect(310, 190, 93, 28))
        self.GoToRegisterButton.setObjectName("GoToRegisterButton")
        self.RegisterWindow = QtWidgets.QWidget()
        self.RegisterWindow.setBaseSize(QtCore.QSize(0, 0))
        self.RegisterWindow.setObjectName("RegisterWindow")
        self.RegisterLabel = QtWidgets.QLabel(self.RegisterWindow)
        self.RegisterLabel.setGeometry(QtCore.QRect(120, 30, 111, 31))
        self.RegisterLabel.setObjectName("RegisterLabel")
        self.RegisterUserNameLabel = QtWidgets.QLabel(self.RegisterWindow)
        self.RegisterUserNameLabel.setGeometry(QtCore.QRect(50, 100, 31, 16))
        self.RegisterUserNameLabel.setObjectName("RegisterUserNameLabel")
        self.RegisterUserPasswordLabel = QtWidgets.QLabel(self.RegisterWindow)
        self.RegisterUserPasswordLabel.setGeometry(QtCore.QRect(50, 140, 31, 16))
        self.RegisterUserPasswordLabel.setObjectName("RegisterUserPasswordLabel")
        self.RegisterUserNickNameLabel = QtWidgets.QLabel(self.RegisterWindow)
        self.RegisterUserNickNameLabel.setGeometry(QtCore.QRect(50, 180, 31, 16))
        self.RegisterUserNickNameLabel.setObjectName("RegisterUserNickNameLabel")
        self.RegisterUserSexLabel = QtWidgets.QLabel(self.RegisterWindow)
        self.RegisterUserSexLabel.setGeometry(QtCore.QRect(50, 220, 31, 16))
        self.RegisterUserSexLabel.setObjectName("RegisterUserSexLabel")
        self.RegisterUserAgeLabel = QtWidgets.QLabel(self.RegisterWindow)
        self.RegisterUserAgeLabel.setGeometry(QtCore.QRect(50, 260, 31, 16))
        self.RegisterUserAgeLabel.setObjectName("RegisterUserAgeLabel")
        self.RegisterUserNameInput = QtWidgets.QLineEdit(self.RegisterWindow)
        self.RegisterUserNameInput.setGeometry(QtCore.QRect(120, 100, 181, 21))
        self.RegisterUserNameInput.setObjectName("RegisterUserNameInput")
        self.RegisterUserPasswordInput = QtWidgets.QLineEdit(self.RegisterWindow)
        self.RegisterUserPasswordInput.setGeometry(QtCore.QRect(120, 140, 181, 21))
        self.RegisterUserPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.RegisterUserPasswordInput.setObjectName("RegisterUserPasswordInput")
        self.RegisterUserNickNameInput = QtWidgets.QLineEdit(self.RegisterWindow)
        self.RegisterUserNickNameInput.setGeometry(QtCore.QRect(120, 180, 181, 21))
        self.RegisterUserNickNameInput.setObjectName("RegisterUserNickNameInput")
        self.RegisterUserAgeInput = QtWidgets.QSpinBox(self.RegisterWindow)
        self.RegisterUserAgeInput.setGeometry(QtCore.QRect(170, 260, 46, 22))
        self.RegisterUserAgeInput.setObjectName("RegisterUserAgeInput")
        self.RegisterUserSexManInput = QtWidgets.QRadioButton(self.RegisterWindow)
        self.RegisterUserSexManInput.setGeometry(QtCore.QRect(140, 220, 51, 19))
        self.RegisterUserSexManInput.setObjectName("RegisterUserSexManInput")
        self.RegisterUserSexWomanInput = QtWidgets.QRadioButton(self.RegisterWindow)
        self.RegisterUserSexWomanInput.setGeometry(QtCore.QRect(230, 220, 51, 20))
        self.RegisterUserSexWomanInput.setObjectName("RegisterUserSexWomanInput")
        self.RegisterButton = QtWidgets.QPushButton(self.RegisterWindow)
        self.RegisterButton.setGeometry(QtCore.QRect(60, 330, 93, 28))
        self.RegisterButton.setObjectName("RegisterButton")
        self.BackToLoginButton = QtWidgets.QPushButton(self.RegisterWindow)
        self.BackToLoginButton.setGeometry(QtCore.QRect(220, 330, 93, 28))
        self.BackToLoginButton.setObjectName("BackToLoginButton")
        self.YizhiWindow = QtWidgets.QWidget()
        self.YizhiWindow.setObjectName("YizhiWindow")
        self.GameDetailBack = QtWidgets.QPushButton(self.YizhiWindow)
        self.GameDetailBack.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.GameDetailBack.setObjectName("GameDetailBack")
        self.Tuixiangzi = QtWidgets.QPushButton(self.YizhiWindow)
        self.Tuixiangzi.setGeometry(QtCore.QRect(320, 150, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Tuixiangzi.setFont(font)
        self.Tuixiangzi.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icon/tuixiangzi.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Tuixiangzi.setIcon(icon6)
        self.Tuixiangzi.setIconSize(QtCore.QSize(45, 45))
        self.Tuixiangzi.setObjectName("Tuixiangzi")
        self.Huarongdao = QtWidgets.QPushButton(self.YizhiWindow)
        self.Huarongdao.setGeometry(QtCore.QRect(320, 230, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Huarongdao.setFont(font)
        self.Huarongdao.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icon/huarongdao.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Huarongdao.setIcon(icon7)
        self.Huarongdao.setIconSize(QtCore.QSize(45, 45))
        self.Huarongdao.setObjectName("Huarongdao")
        self.Lianliankan = QtWidgets.QPushButton(self.YizhiWindow)
        self.Lianliankan.setGeometry(QtCore.QRect(320, 310, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Lianliankan.setFont(font)
        self.Lianliankan.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icon/lianliankan.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Lianliankan.setIcon(icon8)
        self.Lianliankan.setIconSize(QtCore.QSize(45, 45))
        self.Lianliankan.setObjectName("Lianliankan")
        self.Zhaobutong = QtWidgets.QPushButton(self.YizhiWindow)
        self.Zhaobutong.setGeometry(QtCore.QRect(320, 390, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Zhaobutong.setFont(font)
        self.Zhaobutong.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Icon/zhaobutong.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Zhaobutong.setIcon(icon9)
        self.Zhaobutong.setIconSize(QtCore.QSize(45, 45))
        self.Zhaobutong.setObjectName("Zhaobutong")
        self.label = QtWidgets.QLabel(self.YizhiWindow)
        self.label.setGeometry(QtCore.QRect(350, 40, 131, 51))
        self.label.setObjectName("label")
        self.TuijianLabel_4 = QtWidgets.QLabel(self.YizhiWindow)
        self.TuijianLabel_4.setGeometry(QtCore.QRect(100, 100, 281, 16))
        self.TuijianLabel_4.setObjectName("TuijianLabel_4")
        self.CelueWindow = QtWidgets.QWidget()
        self.CelueWindow.setObjectName("CelueWindow")
        self.GameDetailBack_2 = QtWidgets.QPushButton(self.CelueWindow)
        self.GameDetailBack_2.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.GameDetailBack_2.setObjectName("GameDetailBack_2")
        self.label_2 = QtWidgets.QLabel(self.CelueWindow)
        self.label_2.setGeometry(QtCore.QRect(360, 40, 131, 51))
        self.label_2.setObjectName("label_2")
        self.Zhiwuda = QtWidgets.QPushButton(self.CelueWindow)
        self.Zhiwuda.setGeometry(QtCore.QRect(290, 390, 211, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Zhiwuda.setFont(font)
        self.Zhiwuda.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Icon/zhiwuda.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Zhiwuda.setIcon(icon10)
        self.Zhiwuda.setIconSize(QtCore.QSize(45, 45))
        self.Zhiwuda.setObjectName("Zhiwuda")
        self.Baoweiluo = QtWidgets.QPushButton(self.CelueWindow)
        self.Baoweiluo.setGeometry(QtCore.QRect(290, 310, 211, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Baoweiluo.setFont(font)
        self.Baoweiluo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Icon/baoweiluo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Baoweiluo.setIcon(icon11)
        self.Baoweiluo.setIconSize(QtCore.QSize(45, 45))
        self.Baoweiluo.setObjectName("Baoweiluo")
        self.Eluosi = QtWidgets.QPushButton(self.CelueWindow)
        self.Eluosi.setGeometry(QtCore.QRect(290, 150, 211, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Eluosi.setFont(font)
        self.Eluosi.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Icon/eluosi.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Eluosi.setIcon(icon12)
        self.Eluosi.setIconSize(QtCore.QSize(45, 45))
        self.Eluosi.setObjectName("Eluosi")
        self.Hongsejing = QtWidgets.QPushButton(self.CelueWindow)
        self.Hongsejing.setGeometry(QtCore.QRect(290, 230, 211, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Hongsejing.setFont(font)
        self.Hongsejing.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Icon/hongsejing.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Hongsejing.setIcon(icon13)
        self.Hongsejing.setIconSize(QtCore.QSize(45, 45))
        self.Hongsejing.setObjectName("Hongsejing")
        self.TuijianLabel = QtWidgets.QLabel(self.CelueWindow)
        self.TuijianLabel.setGeometry(QtCore.QRect(130, 100, 281, 16))
        self.TuijianLabel.setObjectName("TuijianLabel")
        self.CeluePaihang = QtWidgets.QPushButton(self.CelueWindow)
        self.CeluePaihang.setGeometry(QtCore.QRect(540, 160, 93, 28))
        self.CeluePaihang.setObjectName("CeluePaihang")
        self.DuizhanWindow = QtWidgets.QWidget()
        self.DuizhanWindow.setObjectName("DuizhanWindow")
        self.GameDetailBack_3 = QtWidgets.QPushButton(self.DuizhanWindow)
        self.GameDetailBack_3.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.GameDetailBack_3.setObjectName("GameDetailBack_3")
        self.label_3 = QtWidgets.QLabel(self.DuizhanWindow)
        self.label_3.setGeometry(QtCore.QRect(340, 40, 131, 51))
        self.label_3.setObjectName("label_3")
        self.CS = QtWidgets.QPushButton(self.DuizhanWindow)
        self.CS.setGeometry(QtCore.QRect(310, 230, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.CS.setFont(font)
        self.CS.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Icon/cs.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CS.setIcon(icon14)
        self.CS.setIconSize(QtCore.QSize(45, 45))
        self.CS.setObjectName("CS")
        self.QuanHuang = QtWidgets.QPushButton(self.DuizhanWindow)
        self.QuanHuang.setGeometry(QtCore.QRect(310, 390, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.QuanHuang.setFont(font)
        self.QuanHuang.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Icon/quanhaung.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QuanHuang.setIcon(icon15)
        self.QuanHuang.setIconSize(QtCore.QSize(45, 45))
        self.QuanHuang.setObjectName("QuanHuang")
        self.Huochairen = QtWidgets.QPushButton(self.DuizhanWindow)
        self.Huochairen.setGeometry(QtCore.QRect(310, 310, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Huochairen.setFont(font)
        self.Huochairen.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Icon/huochairen.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Huochairen.setIcon(icon16)
        self.Huochairen.setIconSize(QtCore.QSize(45, 45))
        self.Huochairen.setObjectName("Huochairen")
        self.TuijianLabel_2 = QtWidgets.QLabel(self.DuizhanWindow)
        self.TuijianLabel_2.setGeometry(QtCore.QRect(90, 100, 281, 16))
        self.TuijianLabel_2.setObjectName("TuijianLabel_2")
        self.DuizhanPaihang = QtWidgets.QPushButton(self.DuizhanWindow)
        self.DuizhanPaihang.setGeometry(QtCore.QRect(530, 160, 93, 28))
        self.DuizhanPaihang.setObjectName("DuizhanPaihang")
        self.Tanchishe = QtWidgets.QPushButton(self.DuizhanWindow)
        self.Tanchishe.setGeometry(QtCore.QRect(310, 150, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Tanchishe.setFont(font)
        self.Tanchishe.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Icon/tanchishe.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Tanchishe.setIcon(icon17)
        self.Tanchishe.setIconSize(QtCore.QSize(45, 45))
        self.Tanchishe.setObjectName("Tanchishe")
        self.ZongheWindow = QtWidgets.QWidget()
        self.ZongheWindow.setObjectName("ZongheWindow")
        self.GameDetailBack_4 = QtWidgets.QPushButton(self.ZongheWindow)
        self.GameDetailBack_4.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.GameDetailBack_4.setObjectName("GameDetailBack_4")
        self.label_4 = QtWidgets.QLabel(self.ZongheWindow)
        self.label_4.setGeometry(QtCore.QRect(340, 40, 131, 51))
        self.label_4.setObjectName("label_4")
        self.Maoxiandao = QtWidgets.QPushButton(self.ZongheWindow)
        self.Maoxiandao.setGeometry(QtCore.QRect(320, 390, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Maoxiandao.setFont(font)
        self.Maoxiandao.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Icon/maoxiandao.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Maoxiandao.setIcon(icon18)
        self.Maoxiandao.setIconSize(QtCore.QSize(45, 45))
        self.Maoxiandao.setObjectName("Maoxiandao")
        self.Doudizhu = QtWidgets.QPushButton(self.ZongheWindow)
        self.Doudizhu.setGeometry(QtCore.QRect(320, 310, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Doudizhu.setFont(font)
        self.Doudizhu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("Icon/doudizhu.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Doudizhu.setIcon(icon19)
        self.Doudizhu.setIconSize(QtCore.QSize(45, 45))
        self.Doudizhu.setObjectName("Doudizhu")
        self.Chaojima = QtWidgets.QPushButton(self.ZongheWindow)
        self.Chaojima.setGeometry(QtCore.QRect(320, 230, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Chaojima.setFont(font)
        self.Chaojima.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("Icon/chaojima.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Chaojima.setIcon(icon20)
        self.Chaojima.setIconSize(QtCore.QSize(45, 45))
        self.Chaojima.setObjectName("Chaojima")
        self.TuijianLabel_3 = QtWidgets.QLabel(self.ZongheWindow)
        self.TuijianLabel_3.setGeometry(QtCore.QRect(90, 100, 281, 16))
        self.TuijianLabel_3.setObjectName("TuijianLabel_3")
        self.ZonghePaihang = QtWidgets.QPushButton(self.ZongheWindow)
        self.ZonghePaihang.setGeometry(QtCore.QRect(540, 160, 93, 28))
        self.ZonghePaihang.setObjectName("ZonghePaihang")
        self.Feijida = QtWidgets.QPushButton(self.ZongheWindow)
        self.Feijida.setGeometry(QtCore.QRect(320, 150, 181, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setUnderline(False)
        self.Feijida.setFont(font)
        self.Feijida.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("Icon/feijida.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Feijida.setIcon(icon21)
        self.Feijida.setIconSize(QtCore.QSize(45, 45))
        self.Feijida.setObjectName("Feijida")
        self.PaihangWindow = QtWidgets.QWidget()
        self.PaihangWindow.setObjectName("PaihangWindow")
        self.Paihangbang = QtWidgets.QLabel(self.PaihangWindow)
        self.Paihangbang.setGeometry(QtCore.QRect(180, 40, 111, 41))
        self.Paihangbang.setObjectName("Paihangbang")
        self.PaihangName = QtWidgets.QLabel(self.PaihangWindow)
        self.PaihangName.setGeometry(QtCore.QRect(180, 100, 111, 21))
        self.PaihangName.setText("")
        self.PaihangName.setAlignment(QtCore.Qt.AlignCenter)
        self.PaihangName.setObjectName("PaihangName")
        self.NO1 = QtWidgets.QLabel(self.PaihangWindow)
        self.NO1.setGeometry(QtCore.QRect(30, 150, 41, 41))
        self.NO1.setObjectName("NO1")
        self.NO2 = QtWidgets.QLabel(self.PaihangWindow)
        self.NO2.setGeometry(QtCore.QRect(30, 230, 41, 41))
        self.NO2.setObjectName("NO2")
        self.NO3 = QtWidgets.QLabel(self.PaihangWindow)
        self.NO3.setGeometry(QtCore.QRect(30, 310, 41, 41))
        self.NO3.setObjectName("NO3")
        self.NO4 = QtWidgets.QLabel(self.PaihangWindow)
        self.NO4.setGeometry(QtCore.QRect(30, 390, 41, 41))
        self.NO4.setObjectName("NO4")
        self.NO5 = QtWidgets.QLabel(self.PaihangWindow)
        self.NO5.setGeometry(QtCore.QRect(30, 470, 41, 41))
        self.NO5.setObjectName("NO5")
        self.Name_1 = QtWidgets.QLabel(self.PaihangWindow)
        self.Name_1.setGeometry(QtCore.QRect(90, 150, 271, 41))
        self.Name_1.setText("")
        self.Name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_1.setObjectName("Name_1")
        self.Score_1 = QtWidgets.QLabel(self.PaihangWindow)
        self.Score_1.setGeometry(QtCore.QRect(390, 150, 72, 41))
        self.Score_1.setText("")
        self.Score_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_1.setObjectName("Score_1")
        self.Name_2 = QtWidgets.QLabel(self.PaihangWindow)
        self.Name_2.setGeometry(QtCore.QRect(90, 230, 271, 41))
        self.Name_2.setText("")
        self.Name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_2.setObjectName("Name_2")
        self.Name_3 = QtWidgets.QLabel(self.PaihangWindow)
        self.Name_3.setGeometry(QtCore.QRect(90, 310, 271, 41))
        self.Name_3.setText("")
        self.Name_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_3.setObjectName("Name_3")
        self.Name_4 = QtWidgets.QLabel(self.PaihangWindow)
        self.Name_4.setGeometry(QtCore.QRect(90, 390, 271, 41))
        self.Name_4.setText("")
        self.Name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_4.setObjectName("Name_4")
        self.Name_5 = QtWidgets.QLabel(self.PaihangWindow)
        self.Name_5.setGeometry(QtCore.QRect(90, 470, 271, 41))
        self.Name_5.setText("")
        self.Name_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_5.setObjectName("Name_5")
        self.Score_2 = QtWidgets.QLabel(self.PaihangWindow)
        self.Score_2.setGeometry(QtCore.QRect(390, 230, 72, 41))
        self.Score_2.setText("")
        self.Score_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_2.setObjectName("Score_2")
        self.Score_3 = QtWidgets.QLabel(self.PaihangWindow)
        self.Score_3.setGeometry(QtCore.QRect(390, 310, 72, 41))
        self.Score_3.setText("")
        self.Score_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_3.setObjectName("Score_3")
        self.Score_4 = QtWidgets.QLabel(self.PaihangWindow)
        self.Score_4.setGeometry(QtCore.QRect(390, 390, 72, 41))
        self.Score_4.setText("")
        self.Score_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_4.setObjectName("Score_4")
        self.Score_5 = QtWidgets.QLabel(self.PaihangWindow)
        self.Score_5.setGeometry(QtCore.QRect(390, 470, 72, 41))
        self.Score_5.setText("")
        self.Score_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Score_5.setObjectName("Score_5")
        self.PaihangBack = QtWidgets.QPushButton(self.PaihangWindow)
        self.PaihangBack.setGeometry(QtCore.QRect(170, 560, 121, 31))
        self.PaihangBack.setObjectName("PaihangBack")

        self.retranslateUi(MdiArea)
        self.Book.clicked.connect(MdiArea.book_click)
        self.Game.clicked.connect(MdiArea.game_click)
        self.Book0.clicked.connect(MdiArea.book_rank_click)
        self.Book1.clicked.connect(MdiArea.book_rank_click)
        self.Book2.clicked.connect(MdiArea.book_rank_click)
        self.Book3.clicked.connect(MdiArea.book_rank_click)
        self.Book4.clicked.connect(MdiArea.book_rank_click)
        self.Book5.clicked.connect(MdiArea.book_rank_click)
        self.Book6.clicked.connect(MdiArea.book_rank_click)
        self.Book7.clicked.connect(MdiArea.book_rank_click)
        self.Book8.clicked.connect(MdiArea.book_rank_click)
        self.Book9.clicked.connect(MdiArea.book_rank_click)
        self.BookBack.clicked.connect(MdiArea.book_back_click)
        self.GameBack.clicked.connect(MdiArea.game_back_click)
        self.ContainBack.clicked.connect(MdiArea.contain_back_click)
        self.Chapter.currentIndexChanged['QString'].connect(MdiArea.choose_chapter)
        self.LoginButton.clicked.connect(MdiArea.login)
        self.GoToRegisterButton.clicked.connect(MdiArea.go_to_register)
        self.RegisterButton.clicked.connect(MdiArea.register)
        self.BackToLoginButton.clicked.connect(MdiArea.back_to_login)
        self.RegisterUserSexManInput.clicked.connect(MdiArea.sex_choosed)
        self.RegisterUserSexWomanInput.clicked.connect(MdiArea.sex_choosed)
        self.yizhi.clicked.connect(MdiArea.yizhi_click)
        self.celue.clicked.connect(MdiArea.celue_click)
        self.duizhan.clicked.connect(MdiArea.duizhan_click)
        self.zonghe.clicked.connect(MdiArea.zonghe_click)
        self.Tuixiangzi.clicked.connect(MdiArea.tuixiangzi_click)
        self.Eluosi.clicked.connect(MdiArea.eluosi_click)
        self.GameDetailBack.clicked.connect(MdiArea.game_detail_back)
        self.GameDetailBack_4.clicked.connect(MdiArea.game_detail_back)
        self.GameDetailBack_3.clicked.connect(MdiArea.game_detail_back)
        self.GameDetailBack_2.clicked.connect(MdiArea.game_detail_back)
        self.Maoxiandao.clicked.connect(MdiArea.coding)
        self.Doudizhu.clicked.connect(MdiArea.coding)
        self.Chaojima.clicked.connect(MdiArea.coding)
        self.Zhiwuda.clicked.connect(MdiArea.coding)
        self.Baoweiluo.clicked.connect(MdiArea.coding)
        self.Hongsejing.clicked.connect(MdiArea.coding)
        self.Lianliankan.clicked.connect(MdiArea.coding)
        self.Huarongdao.clicked.connect(MdiArea.coding)
        self.Zhaobutong.clicked.connect(MdiArea.coding)
        self.CS.clicked.connect(MdiArea.coding)
        self.Huochairen.clicked.connect(MdiArea.coding)
        self.QuanHuang.clicked.connect(MdiArea.coding)
        self.ZonghePaihang.clicked.connect(MdiArea.zonghepaihang_click)
        self.DuizhanPaihang.clicked.connect(MdiArea.duizhanpaihang_click)
        self.CeluePaihang.clicked.connect(MdiArea.celuepaihang_click)
        self.PaihangBack.clicked.connect(MdiArea.paihang_back_click)
        self.Tanchishe.clicked.connect(MdiArea.tanchishe_click)
        self.Feijida.clicked.connect(MdiArea.feijida_click)
        QtCore.QMetaObject.connectSlotsByName(MdiArea)

    def retranslateUi(self, MdiArea):
        _translate = QtCore.QCoreApplication.translate
        MdiArea.setWindowTitle(_translate("MdiArea", "MdiArea"))
        self.MainWindow.setWindowTitle(_translate("MdiArea", "主界面"))
        self.Book.setText(_translate("MdiArea", "名著阅读"))
        self.Game.setText(_translate("MdiArea", "游戏娱乐"))
        self.WelcomeAndName.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:16pt;\">欢迎</span></p></body></html>"))
        self.LvLabel.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:24pt;\">LV</span></p></body></html>"))
        self.BookWindow.setWindowTitle(_translate("MdiArea", "名著阅读"))
        self.mingzhupaihang.setText(_translate("MdiArea", "名著排行"))
        self.Book0.setText(_translate("MdiArea", "PushButton"))
        self.Book1.setText(_translate("MdiArea", "PushButton"))
        self.Book2.setText(_translate("MdiArea", "PushButton"))
        self.Book3.setText(_translate("MdiArea", "PushButton"))
        self.Book4.setText(_translate("MdiArea", "PushButton"))
        self.Book5.setText(_translate("MdiArea", "PushButton"))
        self.Book6.setText(_translate("MdiArea", "PushButton"))
        self.Book7.setText(_translate("MdiArea", "PushButton"))
        self.Book8.setText(_translate("MdiArea", "PushButton"))
        self.Book9.setText(_translate("MdiArea", "PushButton"))
        self.BookBack.setText(_translate("MdiArea", "返回"))
        self.GameWindow.setWindowTitle(_translate("MdiArea", "游戏盒子"))
        self.GameBack.setText(_translate("MdiArea", "返回"))
        self.youxiyule.setText(_translate("MdiArea", "游戏娱乐"))
        self.yizhi.setText(_translate("MdiArea", "益智类"))
        self.celue.setText(_translate("MdiArea", "策略类"))
        self.duizhan.setText(_translate("MdiArea", "对战类"))
        self.zonghe.setText(_translate("MdiArea", "综合类"))
        self.ContainWindow.setWindowTitle(_translate("MdiArea", "名著阅读"))
        self.ContainBack.setText(_translate("MdiArea", "返回"))
        self.LoginWindow.setWindowTitle(_translate("MdiArea", "登陆"))
        self.UserNameLabel.setText(_translate("MdiArea", "用户名"))
        self.UserPasswordLabel.setText(_translate("MdiArea", "密码"))
        self.WelcomeLabel.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; color:#9e1f1b;\">欢迎来到金院游戏中心</span></p></body></html>"))
        self.LoginButton.setText(_translate("MdiArea", "登陆"))
        self.GoToRegisterButton.setText(_translate("MdiArea", "注册"))
        self.RegisterWindow.setWindowTitle(_translate("MdiArea", "注册"))
        self.RegisterLabel.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:16pt; color:#04ccbc;\">欢迎注册</span></p></body></html>"))
        self.RegisterUserNameLabel.setText(_translate("MdiArea", "账号"))
        self.RegisterUserPasswordLabel.setText(_translate("MdiArea", "密码"))
        self.RegisterUserNickNameLabel.setText(_translate("MdiArea", "昵称"))
        self.RegisterUserSexLabel.setText(_translate("MdiArea", "性别"))
        self.RegisterUserAgeLabel.setText(_translate("MdiArea", "年龄"))
        self.RegisterUserSexManInput.setText(_translate("MdiArea", "男生"))
        self.RegisterUserSexWomanInput.setText(_translate("MdiArea", "女生"))
        self.RegisterButton.setText(_translate("MdiArea", "注册"))
        self.BackToLoginButton.setText(_translate("MdiArea", "返回登录"))
        self.YizhiWindow.setWindowTitle(_translate("MdiArea", "益智类"))
        self.GameDetailBack.setText(_translate("MdiArea", "返回"))
        self.Tuixiangzi.setText(_translate("MdiArea", "推箱子"))
        self.Huarongdao.setText(_translate("MdiArea", "华容道"))
        self.Lianliankan.setText(_translate("MdiArea", "连连看"))
        self.Zhaobutong.setText(_translate("MdiArea", "找不同"))
        self.label.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:18pt;\">益智游戏</span></p></body></html>"))
        self.TuijianLabel_4.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:11pt;\">根据您经常玩的游戏，为您推荐了：</span></p></body></html>"))
        self.CelueWindow.setWindowTitle(_translate("MdiArea", "策略类"))
        self.GameDetailBack_2.setText(_translate("MdiArea", "返回"))
        self.label_2.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:18pt;\">策略游戏</span></p></body></html>"))
        self.Zhiwuda.setText(_translate("MdiArea", "植物大战僵尸"))
        self.Baoweiluo.setText(_translate("MdiArea", "  保卫萝卜  "))
        self.Eluosi.setText(_translate("MdiArea", " 俄罗斯方块 "))
        self.Hongsejing.setText(_translate("MdiArea", "  红色警戒  "))
        self.TuijianLabel.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:11pt;\">根据您经常玩的游戏，为您推荐了：</span></p></body></html>"))
        self.CeluePaihang.setText(_translate("MdiArea", "排行榜"))
        self.DuizhanWindow.setWindowTitle(_translate("MdiArea", "对战类"))
        self.GameDetailBack_3.setText(_translate("MdiArea", "返回"))
        self.label_3.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:18pt;\">对战游戏</span></p></body></html>"))
        self.CS.setText(_translate("MdiArea", "  CS  "))
        self.QuanHuang.setText(_translate("MdiArea", " 拳皇 "))
        self.Huochairen.setText(_translate("MdiArea", "火柴人"))
        self.TuijianLabel_2.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:11pt;\">根据您经常玩的游戏，为您推荐了：</span></p></body></html>"))
        self.DuizhanPaihang.setText(_translate("MdiArea", "排行榜"))
        self.Tanchishe.setText(_translate("MdiArea", "贪吃蛇"))
        self.ZongheWindow.setWindowTitle(_translate("MdiArea", "综合类"))
        self.GameDetailBack_4.setText(_translate("MdiArea", "返回"))
        self.label_4.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:18pt;\">综合游戏</span></p></body></html>"))
        self.Maoxiandao.setText(_translate("MdiArea", " 冒险岛 "))
        self.Doudizhu.setText(_translate("MdiArea", " 斗地主 "))
        self.Chaojima.setText(_translate("MdiArea", "超级玛丽"))
        self.TuijianLabel_3.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:11pt;\">根据您经常玩的游戏，为您推荐了：</span></p></body></html>"))
        self.ZonghePaihang.setText(_translate("MdiArea", "排行榜"))
        self.Feijida.setText(_translate("MdiArea", "飞机大战"))
        self.PaihangWindow.setWindowTitle(_translate("MdiArea", "排行"))
        self.Paihangbang.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:22pt;\">排行榜</span></p></body></html>"))
        self.NO1.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:28pt; color:#000000;\">1.</span></p></body></html>"))
        self.NO2.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:28pt; color:#000000;\">2.</span></p></body></html>"))
        self.NO3.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:28pt; color:#000000;\">3.</span></p></body></html>"))
        self.NO4.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:28pt; color:#000000;\">4.</span></p></body></html>"))
        self.NO5.setText(_translate("MdiArea", "<html><head/><body><p><span style=\" font-size:28pt; color:#000000;\">5.</span></p></body></html>"))
        self.PaihangBack.setText(_translate("MdiArea", "返回"))

